name: Build Cross-Platform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --console ^
          --hidden-import=selenium ^
          --hidden-import=selenium.webdriver ^
          --hidden-import=selenium.webdriver.chrome ^
          --hidden-import=selenium.webdriver.chrome.service ^
          --hidden-import=selenium.webdriver.common.by ^
          --hidden-import=selenium.webdriver.common.action_chains ^
          --hidden-import=selenium_stealth ^
          --hidden-import=webdriver_manager ^
          --hidden-import=webdriver_manager.chrome ^
          --hidden-import=bs4 ^
          --hidden-import=requests ^
          --hidden-import=lxml ^
          --name fb-scraper-windows ^
          "1 (2).py"
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/fb-scraper-windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --console \
          --hidden-import=selenium \
          --hidden-import=selenium.webdriver \
          --hidden-import=selenium.webdriver.chrome \
          --hidden-import=selenium.webdriver.chrome.service \
          --hidden-import=selenium.webdriver.common.by \
          --hidden-import=selenium.webdriver.common.action_chains \
          --hidden-import=selenium_stealth \
          --hidden-import=webdriver_manager \
          --hidden-import=webdriver_manager.chrome \
          --hidden-import=bs4 \
          --hidden-import=requests \
          --hidden-import=lxml \
          --name fb-scraper-macos \
          "1 (2).py"
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/fb-scraper-macos
